# path or URL to sample sheet (TSV format, columns: sample, condition, ...)
samples: config/samples.tsv
# path or URL to sequencing unit sheet (TSV format, columns: sample, unit, fq1, fq2)
# Units are technical replicates (e.g. lanes, or resequencing of the same biological
# sample).
units: config/units.tsv

# optional inclusion of certain rules -------------------------------------------------------
mergeReads:
  activate: True

# text file containing list of chromosomes to keep when filtering ---------------------------
filter_chroms: True
keep_chroms: config/keep_chroms.txt

# reference genome options ------------------------------------------------------------------
use_spikeIn: False
ref_genome:
  name: dm6
  link: https://hgdownload.soe.ucsc.edu/goldenPath/dm6/bigZips/dm6.fa.gz

# spike-in genome options ------------------------------------------------------------------
use_spikeIn: False

spikeIn_genome:
  name: yeast_w303
  link: http://sgd-archive.yeastgenome.org/sequence/strains/W303/W303_SGD_2015_JRIU00000000/W303_SGD_2015_JRIU00000000.fsa.gz




# changes to rule paramters ---------------------------------------------------------------
params:
  cutadapt-pe: ""
  cutadapt-se: ""
  star: ""
